### ISSUE TITLE
Worker not found

### ISSUE THREAD

**Issue by wormen** [rotemdan/lzutf8.js#22]
![image](https://user-images.githubusercontent.com/8462339/67368352-22e61a80-f5b2-11e9-93dc-63f518a64ae5.png)

**Comment by rotemdan** [comment]
Hi, based on the output I'm assuming you're trying to consume the library in your own code (rather than compiling it by itself).

Seems like the typescript compiler is looking into the `node_modules` directory and finding the declaration file bundled with the build (it is auto-generated when the library is compiled) and erroring when it can't find a definition for the `Worker` interface.

If scanning the lzutf8 declaration file is not desired, I guess in `tsconfig.json` you can add:
```json
	"exclude": [
		"node_modules"
	]
```

If it is desired, than in your project's `tsconfig.json` try adding `"webworker"` under `"lib"`:
```json
"compilerOptions": {
	"lib": [
		"webworker"
	]
},
```
Adding `"dom"` also seems to work (the library's tsconfig uses it).

An alternative is in the `tsc` command line add `--lib webworker` like this:
```
tsc --lib webworker
```

**Comment by wormen** [comment]
yes it works
thanks
