### ISSUE TITLE
Chance to optimize the bundle size?

### ISSUE THREAD

**Issue by chunlaw** [rotemdan/lzutf8.js#47]
It is no doubt that lzutf8 is way faster than lz-string. However, the bundle size of lzutf8 is ~80KB, compared to lz-string is just ~5KB.

Would you consider to optimize the bundle size, esp., `readable-stream` contributes ~40% of bundle size.

**Comment by rotemdan** [comment]
Hi, the documentation you're reading was written in 2014. Since then many other compression libraries appeared. Many of which are better alternatives to this one (faster and better compression ratios), especially ones optimized on WebAssembly (I can't give you exact names though).

The comparison with `lz-string` is not relevant anymore. 

The library is out-of-date and not actively maintained. It will require a full rewrite to update for newer technologies. I don't have time for that unfortunately.

I am considering adding a deprecation notice to the readme. Still thinking about the wording for now.

**Comment by rotemdan** [comment]
I added a deprecation note to the readme file.

**Comment by chunlaw** [comment]
Although it is deprecated, it is really a great work. The performance is still faster than `lz-string` for 3x-6x times. Anyway, thank you for your great contributions.
